import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    'nav.discover': 'Découvrir',
    'nav.login': 'Se connecter',
    'nav.signup': "S'inscrire",
    'nav.profile': 'Profil',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',
    'hero.title': 'Découvrez les saveurs de',
    'hero.subtitle': 'Réservez une table ou commandez vos plats préférés dans les meilleurs établissements de la côte.',
    'hero.search_placeholder': 'Que voulez-vous manger ?',
    'hero.search_button': 'Rechercher',
    'home.featured': 'Les incontournables',
    'home.featured_subtitle': 'Les établissements les plus populaires du moment.',
    'home.view_all': 'Voir tout',
    'home.partner_title': "Vous êtes propriétaire d'un restaurant à Saly ou Mbour ?",
    'home.partner_subtitle': 'Rejoignez SalyFood pour booster votre visibilité, gérer vos réservations et proposer la livraison à vos clients.',
    'home.partner_button': 'Inscrire mon établissement',
    'home.learn_more': 'En savoir plus',
    'footer.description': 'La plateforme de référence pour découvrir et commander les meilleurs plats à Saly et Mbour.',
    'footer.platform': 'Plateforme',
    'footer.support': 'Support',
    'footer.about': 'À propos',
    'footer.restaurants': 'Restaurants',
    'footer.partnership': 'Devenir partenaire',
    'footer.help': 'Aide',
    'footer.contact': 'Contact',
    'footer.terms': "Conditions d'utilisation",
    'cat.restaurants': 'Restaurants',
    'cat.glaciers': 'Glaciers',
    'cat.cafes': 'Cafés',
    'cat.snacks': 'Snacks',
    'home.no_results': 'Aucun établissement trouvé pour le moment.',
    'login.title_login': 'Bon retour !',
    'login.title_signup': 'Créer un compte',
    'login.subtitle_login': 'Connectez-vous pour accéder à vos favoris et commandes.',
    'login.subtitle_signup': "Rejoignez la communauté SalyFood dès aujourd'hui.",
    'login.fullname': 'Nom complet',
    'login.password': 'Mot de passe',
    'login.loading': 'Chargement...',
    'login.or_continue': 'Ou continuer avec',
    'login.already_account': 'Déjà un compte ?',
    'login.no_account': 'Pas encore de compte ?',
    'profile.login_prompt': 'Veuillez vous connecter.',
    'profile.orders': 'Commandes',
    'profile.reservations': 'Réservations',
    'profile.settings': 'Paramètres',
    'profile.order_history': 'Historique des commandes',
    'profile.order_id': 'Commande',
    'profile.reservation_for': 'Réservation pour',
    'profile.your_reservations': 'Vos réservations',
    'profile.no_orders': "Vous n'avez pas encore passé de commande.",
    'profile.no_reservations': 'Aucune réservation en cours.',
    'nav.notifications': 'Notifications',
    'nav.unread': 'non lues',
    'nav.no_notifications': 'Aucune notification',
    'nav.my_restaurant': 'Mon Restaurant',
    'nav.admin': 'Admin',
    'discover.title': 'Découvrir',
    'discover.subtitle': 'Explorez les meilleurs endroits pour manger à Saly et Mbour.',
    'discover.list': 'Liste',
    'discover.map': 'Carte',
    'discover.filters': 'Filtres',
    'discover.reset': 'Réinitialiser',
    'discover.category': 'Catégorie',
    'discover.city': 'Ville',
    'discover.price': 'Prix',
    'discover.no_results': 'Aucun résultat',
    'discover.no_results_subtitle': 'Essayez de modifier vos filtres pour trouver ce que vous cherchez.',
    'discover.interactive_map': 'Carte interactive',
    'discover.visualize_all': 'Visualisez tous les établissements de Saly et Mbour.',
    'discover.view_profile': 'Voir le profil',
    'admin.title': 'Administration',
    'admin.approvals': 'Approbations',
    'admin.stats': 'Statistiques',
    'admin.establishments': 'Établissements',
    'admin.users': 'Utilisateurs',
    'admin.pending_approvals': 'Approbations en attente',
    'admin.platform_revenue': 'Revenus Plateforme',
    'admin.approval_requests': "Demandes d'approbation",
    'admin.no_pending': 'Aucune demande en attente.',
    'admin.distribution': 'Répartition par catégorie',
    'admin.latest_registered': 'Derniers établissements inscrits',
    'admin.loading': "Chargement de l'administration...",
    'admin.status': 'Statut',
    'restaurant.dashboard': 'Tableau de bord',
    'restaurant.menu': 'Menu',
    'restaurant.orders': 'Commandes',
    'restaurant.reservations': 'Réservations',
    'restaurant.settings': 'Paramètres',
    'restaurant.add_item': 'Ajouter un plat',
    'restaurant.edit_item': 'Modifier le plat',
    'restaurant.no_items': 'Aucun plat dans votre menu.',
    'restaurant.no_orders': 'Aucune commande reçue.',
    'restaurant.no_reservations': 'Aucune réservation reçue.',
    'restaurant.loading': 'Chargement du tableau de bord...',
    'restaurant.no_business': "Vous n'avez pas encore d'établissement enregistré.",
    'restaurant.overview': "Vue d'ensemble",
    'restaurant.orders_today': 'Commandes du jour',
    'restaurant.revenue': 'Revenus (CFA)',
    'restaurant.avg_rating': 'Note moyenne',
    'restaurant.qr_title': 'Votre QR Code Menu',
    'restaurant.download': 'Télécharger',
    'restaurant.qr_desc': 'Imprimez ce QR code et placez-le sur vos tables. Vos clients pourront scanner le code pour voir votre menu et commander directement depuis leur téléphone.',
    'restaurant.order_mgmt': 'Gestion des commandes',
    'restaurant.menu_mgmt': 'Gestion du menu',
    'restaurant.table_res': 'Réservations de tables',
    'restaurant.accept': 'Accepter',
    'restaurant.prepare': 'Préparer',
    'restaurant.ready': 'Prêt',
    'restaurant.delivered': 'Livré',
    'restaurant.confirm': 'Confirmer',
    'restaurant.refuse': 'Refuser',
    'restaurant.dish_name': 'Nom du plat',
    'restaurant.price_cfa': 'Prix (CFA)',
    'restaurant.category': 'Catégorie',
    'restaurant.add_to_menu': 'Ajouter au menu',
    'restaurant.items': 'articles',
    'restaurant.table_for': 'Table pour',
    'restaurant.people': 'personnes',
    'profile.about': 'À propos',
    'profile.the_menu': 'Le Menu',
    'profile.no_menu': "Le menu n'est pas encore disponible.",
    'profile.reviews': 'Avis des clients',
    'profile.leave_review': 'Laisser un avis',
    'profile.share_exp': 'Partagez votre expérience...',
    'profile.publish': 'Publier',
    'profile.sending': 'Envoi...',
    'profile.no_reviews': 'Aucun avis pour le moment.',
    'profile.info': 'Informations',
    'profile.opening_hours': "Horaires d'ouverture",
    'profile.delivery': 'Livraison',
    'profile.dine_in': 'Sur place',
    'profile.takeaway': 'À emporter',
    'profile.your_cart': 'Votre Panier',
    'profile.order_now': 'Commander maintenant',
    'profile.checkout': 'Finaliser la commande',
    'profile.pickup_method': 'Mode de retrait',
    'profile.free': 'Gratuit',
    'profile.subtotal': 'Sous-total',
    'profile.reserve_table': 'Réserver une table',
    'profile.date_time': 'Date et Heure',
    'profile.num_people': 'Nombre de personnes',
    'profile.confirm_request': 'Confirmer la demande',
    'profile.order_success': 'Commande envoyée avec succès !',
    'profile.res_success': 'Demande de réservation envoyée !',
    'profile.new_order': 'Nouvelle commande',
    'profile.new_res': 'Nouvelle réservation',
    'profile.new_order_msg': 'Vous avez reçu une nouvelle commande de {name}.',
    'profile.new_res_msg': '{name} souhaite réserver une table pour {guests} personnes.',
    'profile.loading': 'Chargement...',
    'profile.not_found': 'Établissement non trouvé.',
  },
  en: {
    'nav.discover': 'Discover',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'hero.title': 'Discover the flavors of',
    'hero.subtitle': 'Book a table or order your favorite dishes from the best establishments on the coast.',
    'hero.search_placeholder': 'What do you want to eat?',
    'hero.search_button': 'Search',
    'home.featured': 'Must-visits',
    'home.featured_subtitle': 'The most popular establishments at the moment.',
    'home.view_all': 'View all',
    'home.partner_title': 'Do you own a restaurant in Saly or Mbour?',
    'home.partner_subtitle': 'Join SalyFood to boost your visibility, manage your reservations and offer delivery to your customers.',
    'home.partner_button': 'Register my establishment',
    'home.learn_more': 'Learn more',
    'footer.description': 'The leading platform for discovering and ordering the best dishes in Saly and Mbour.',
    'footer.platform': 'Platform',
    'footer.support': 'Support',
    'footer.about': 'About',
    'footer.restaurants': 'Restaurants',
    'footer.partnership': 'Become a partner',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.terms': 'Terms of use',
    'cat.restaurants': 'Restaurants',
    'cat.glaciers': 'Ice Cream',
    'cat.cafes': 'Cafes',
    'cat.snacks': 'Snacks',
    'home.no_results': 'No establishments found at the moment.',
    'login.title_login': 'Welcome back!',
    'login.title_signup': 'Create an account',
    'login.subtitle_login': 'Log in to access your favorites and orders.',
    'login.subtitle_signup': 'Join the SalyFood community today.',
    'login.fullname': 'Full name',
    'login.password': 'Password',
    'login.loading': 'Loading...',
    'login.or_continue': 'Or continue with',
    'login.already_account': 'Already have an account?',
    'login.no_account': 'No account yet?',
    'profile.login_prompt': 'Please log in.',
    'profile.orders': 'Orders',
    'profile.reservations': 'Reservations',
    'profile.settings': 'Settings',
    'profile.order_history': 'Order History',
    'profile.order_id': 'Order',
    'profile.reservation_for': 'Reservation for',
    'profile.your_reservations': 'Your Reservations',
    'profile.no_orders': "You haven't placed any orders yet.",
    'profile.no_reservations': 'No reservations in progress.',
    'nav.notifications': 'Notifications',
    'nav.unread': 'unread',
    'nav.no_notifications': 'No notifications',
    'nav.my_restaurant': 'My Restaurant',
    'nav.admin': 'Admin',
    'discover.title': 'Discover',
    'discover.subtitle': 'Explore the best places to eat in Saly and Mbour.',
    'discover.list': 'List',
    'discover.map': 'Map',
    'discover.filters': 'Filters',
    'discover.reset': 'Reset',
    'discover.category': 'Category',
    'discover.city': 'City',
    'discover.price': 'Price',
    'discover.no_results': 'No results',
    'discover.no_results_subtitle': 'Try changing your filters to find what you are looking for.',
    'discover.interactive_map': 'Interactive Map',
    'discover.visualize_all': 'Visualize all establishments in Saly and Mbour.',
    'discover.view_profile': 'View profile',
    'admin.title': 'Administration',
    'admin.approvals': 'Approvals',
    'admin.stats': 'Statistics',
    'admin.establishments': 'Establishments',
    'admin.users': 'Users',
    'admin.pending_approvals': 'Pending Approvals',
    'admin.platform_revenue': 'Platform Revenue',
    'admin.approval_requests': 'Approval Requests',
    'admin.no_pending': 'No pending requests.',
    'admin.distribution': 'Distribution by category',
    'admin.latest_registered': 'Latest registered establishments',
    'admin.loading': 'Loading administration...',
    'admin.status': 'Status',
    'restaurant.dashboard': 'Dashboard',
    'restaurant.menu': 'Menu',
    'restaurant.orders': 'Orders',
    'restaurant.reservations': 'Reservations',
    'restaurant.settings': 'Settings',
    'restaurant.add_item': 'Add item',
    'restaurant.edit_item': 'Edit item',
    'restaurant.no_items': 'No items in your menu.',
    'restaurant.no_orders': 'No orders received.',
    'restaurant.no_reservations': 'No reservations received.',
    'restaurant.loading': 'Loading dashboard...',
    'restaurant.no_business': "You don't have a registered establishment yet.",
    'restaurant.overview': 'Overview',
    'restaurant.orders_today': "Today's Orders",
    'restaurant.revenue': 'Revenue (CFA)',
    'restaurant.avg_rating': 'Average Rating',
    'restaurant.qr_title': 'Your Menu QR Code',
    'restaurant.download': 'Download',
    'restaurant.qr_desc': 'Print this QR code and place it on your tables. Your customers can scan the code to view your menu and order directly from their phone.',
    'restaurant.order_mgmt': 'Order Management',
    'restaurant.menu_mgmt': 'Menu Management',
    'restaurant.table_res': 'Table Reservations',
    'restaurant.accept': 'Accept',
    'restaurant.prepare': 'Prepare',
    'restaurant.ready': 'Ready',
    'restaurant.delivered': 'Delivered',
    'restaurant.confirm': 'Confirm',
    'restaurant.refuse': 'Refuse',
    'restaurant.dish_name': 'Dish name',
    'restaurant.price_cfa': 'Price (CFA)',
    'restaurant.category': 'Category',
    'restaurant.add_to_menu': 'Add to menu',
    'restaurant.items': 'items',
    'restaurant.table_for': 'Table for',
    'restaurant.people': 'people',
    'profile.about': 'About',
    'profile.the_menu': 'The Menu',
    'profile.no_menu': 'The menu is not available yet.',
    'profile.reviews': 'Customer Reviews',
    'profile.leave_review': 'Leave a review',
    'profile.share_exp': 'Share your experience...',
    'profile.publish': 'Publish',
    'profile.sending': 'Sending...',
    'profile.no_reviews': 'No reviews yet.',
    'profile.info': 'Information',
    'profile.opening_hours': 'Opening Hours',
    'profile.delivery': 'Delivery',
    'profile.dine_in': 'Dine-in',
    'profile.takeaway': 'Takeaway',
    'profile.your_cart': 'Your Cart',
    'profile.order_now': 'Order now',
    'profile.checkout': 'Checkout',
    'profile.pickup_method': 'Pickup Method',
    'profile.free': 'Free',
    'profile.subtotal': 'Subtotal',
    'profile.reserve_table': 'Reserve a table',
    'profile.date_time': 'Date and Time',
    'profile.num_people': 'Number of people',
    'profile.confirm_request': 'Confirm request',
    'profile.order_success': 'Order sent successfully!',
    'profile.res_success': 'Reservation request sent!',
    'profile.new_order': 'New order',
    'profile.new_res': 'New reservation',
    'profile.new_order_msg': 'You received a new order from {name}.',
    'profile.new_res_msg': '{name} wants to reserve a table for {guests} people.',
    'profile.loading': 'Loading...',
    'profile.not_found': 'Establishment not found.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
